# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_minibatch_training.ipynb.

# %% auto 0
__all__ = ['accuracy', 'report', 'Dataset']

# %% ../nbs/01_minibatch_training.ipynb 1
import pickle,gzip,math,os,time,shutil,torch,matplotlib as mpl,numpy as np,matplotlib.pyplot as plt
from pathlib import Path
from torch import tensor,nn
import torch.nn.functional as F

# %% ../nbs/01_minibatch_training.ipynb 31
def accuracy(out, yb): return (out.argmax(dim=1) == yb).float().mean()

# %% ../nbs/01_minibatch_training.ipynb 34
def report(loss, preds, yb): print(f'{loss:.2f}, {accuracy(preds, yb):.2f}')

# %% ../nbs/01_minibatch_training.ipynb 80
class Dataset():
    def __init__(self, x, y): self.x, self.y = x, y
    def __len__(self): return len(self.x)
    def __getitem__(self, i): return self.x[i], self.y[i]

# %% ../nbs/01_minibatch_training.ipynb 126
from torch.utils.data import DataLoader, SequentialSampler, RandomSampler, BatchSampler
